#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
 
#  check if mongodb is disponible
echo "Starting Flask application setup... "
# flask db downgrade 1d679b98d407
# Run database migrations
echo "Running database migrations..."
# flask db upgrade

echo "Flask application starting..."

# Start Flask application
flask run --host=0.0.0.0 --port="${flask_listening_port:-5001}"

exec "$@"

